### ISSUE TITLE
Incorrect format of `cmpi` instruction

### ISSUE THREAD

**Issue by crispy-strawberry** [orbit-systems/aphelion#5]
In the manual, the `cmpi`(0x1F) instruction uses the `M` encoding format but the implementations (C, Zig et al) use the `F` encoding format.
This is probably already known but just posting here for publicity.

**Comment by spsandwichman** [comment]
my bad, this spec is outdated actually. I'll update it with the newest version as soon as I can!

**Comment by spsandwichman** [comment]
its been updated, along with the readme. we have a dev discord if you'd like to join, it's linked in the organization's description :p
